# Generated by Django 6.1.1 on 2026-09-11 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('login_failed', 'Login failed'), ('note_created', 'Note created'), ('note_viewed', 'Note viewed'), ('note_updated', 'Note updated'), ('note_deleted', 'Note deleted'), ('note_shared', 'Note shared'), ('user_created', 'User created'), ('user_role_changed', 'User role changed'), ('user_deactivated', 'User deactivated'), ('user_deleted', 'User deleted (self-service)')], max_length=32),
        ),
    ]
